#include "TrustModelBridge.h"
#include "AVLTree.h"
#include "MatchmakingEngine.h"
#include "Player.h"

#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

struct PlayerTrustInput
{
    Player player;
    TrustFeatures features;
};

int main()
{
    std::cout << "============================================\n";
    std::cout << "   NEXUSMATCH ML TRUST + C++ MATCHMAKING\n";
    std::cout << "============================================\n";

    // All players use the same matchmaking context here so that the
    // effect of ML-generated Trust is easy to observe.
    PlayerTrustInput players[] =
    {
        {
            Player(101, "Amish", 1520, "India", "Ranked", 50, 100),
            {20, 0.95, 0.05, 0.90, 0.05, 0.90,
             1.00, 0.00, 1.00, 0.00, 1.00,
             25, 50, 3}
        },
        {
            Player(102, "Gurveer", 1520, "India", "Ranked", 50, 100),
            {20, 0.80, 0.20, 0.80, 0.15, 0.70,
             0.67, 0.33, 0.67, 0.33, 0.50,
             30, 50, 3}
        },
        {
            Player(103, "Riya", 1520, "India", "Ranked", 50, 100),
            {20, 0.98, 0.02, 0.95, 0.02, 0.95,
             1.00, 0.00, 1.00, 0.00, 1.00,
             24, 50, 3}
        },
        {
            Player(104, "Player4", 1520, "India", "Ranked", 50, 100),
            {20, 0.40, 0.60, 0.30, 0.70, 0.20,
             0.33, 0.67, 0.33, 0.67, 0.00,
             60, 50, 2}
        }
    };

    TrustModelBridge bridge;

    std::cout << "\n========== ML TRUST PREDICTIONS ==========" << "\n";
    std::cout << std::fixed << std::setprecision(2);

    for (auto& item : players)
    {
        TrustResult result{};
        std::string error;

        if (!bridge.predict(item.features, result, error))
        {
            std::cerr << "Trust prediction failed for "
                      << item.player.getName() << ": "
                      << error << "\n";
            return 1;
        }

        item.player.setTrustScore(
            static_cast<int>(result.trustScore + 0.5)
        );

        std::cout
            << item.player.getName()
            << " | Risk: " << result.unreliableRisk
            << " | Trust: " << result.trustScore
            << " | Label: " << result.label
            << "\n";
    }

    // Load the ML-enriched Player objects into the Phase 1 skill index.
    AVLTree skillTree;
    for (const auto& item : players)
    {
        skillTree.insert(item.player);
    }

    MatchmakingEngine matchmaking;
    std::vector<Player> matchedPlayers;

    const Player anchor = players[0].player;

    bool success = matchmaking.findGroupMatch(
        anchor,
        skillTree,
        3,
        matchedPlayers
    );

    if (!success)
    {
        std::cerr << "\nNo compatible match was found.\n";
        return 1;
    }

    std::cout << "\n========== TRUST-AWARE MATCH ==========" << "\n";
    for (std::size_t i = 0; i < matchedPlayers.size(); ++i)
    {
        const Player& player = matchedPlayers[i];
        std::cout
            << (i + 1) << ". "
            << player.getName()
            << " | Skill: " << player.getSkill()
            << " | Trust: " << player.getTrustScore()
            << "\n";
    }

    std::cout << "\nTrust is now generated by the ML model and consumed";
    std::cout << "\nby the C++ MatchmakingEngine.\n";

    return 0;
}