services:
  nexusmatch-server:
    build:
      context: ../../..
      dockerfile: Phase2/TrustSystem/docker/Dockerfile
    container_name: nexusmatch-server
    ports:
      - "5050:5050"
    restart: "no"

  player-simulation:
    build:
      context: ../../..
      dockerfile: Phase2/TrustSystem/docker/Dockerfile.client
    container_name: nexusmatch-player-simulation
    environment:
      NEXUSMATCH_SERVER_HOST: nexusmatch-server
      NEXUSMATCH_SERVER_PORT: "5050"
    depends_on:
      - nexusmatch-server
    restart: "no"
